### ISSUE TITLE
Bug: infinite loop in `CalendarDateUntil` calculation

### ISSUE THREAD

**Issue by nekevss** [boa-dev/temporal#29]
While migrating Boa to `temporal_rs` in boa-dev/boa#3694, an infinite loop was discovered in the `calendar.prototype.dateUntil` test suite.

Cause: most likely occurs [here](https://github.com/boa-dev/temporal/blob/main/src/iso.rs#L243) in the `diff_iso_date` function.

Test 262 tests: The loop occurs in the [largest-unit-year.js](https://github.com/tc39/test262/blob/main/test/built-ins/Temporal/Calendar/prototype/dateUntil/largest-unit-year.js) tests.

**Comment by jedel1043** [comment]
Would be good to port the test from JS to native Rust
