### ISSUE TITLE
Remove custom calendars & timezones

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/temporal#64]
After discussion in the last TC39 plenary, it was confirmed there won't be any custom calendar usage with Temporal. Even if this was to return in a V2, it wouldn't come back in the same shape we see today. Functionality could be injected at a lower level (similar to Timezones with tzdatabase).

Despite this being a library to power higher-level ECMAScript implementations it should still try to follow the Temporal specification as much as possible and not include things the spec doesn't make use of. We can also add extra functionality further down the line in other areas.

**Comment by jedel1043** [comment]
Agreed with this. We could start by removing `Calendar` and `Timezone` first until the code compiles again, then make another pass when the spec proposal changes, since I would expect that some code paths around `NaiveDate` and `ZonedDateTime` will also be removed thanks to the changes.
